### ISSUE TITLE
Strange sentences

### ISSUE THREAD

**Issue by wolftune** [S3-working-group/s3-practical-guide#1]
> inquire to better understand the feedback, and avoid to discuss or judge it

From peer-development/peer-feedback.md

The second half is a strange wording. "Avoid to discuss" and "avoid to judge" are not standard English syntax. Perhaps "avoid discussing or judging" or "…feedback, avoiding discussion or judgment of it"

But with those fixes, it's still strange semantically. Inquire but don't discuss? What does that mean? Is the point to not be picky about the wording of the feedback as long as you end up understanding the intent?

---

Later in peer-development/peer-review.md

> Ensure to invite people with complementing perspectives…

That's odd syntax too. "Ensure to invite" isn't standard English. Perhaps "ensure you invite" or "Be sure to invite".

Also "complementing perspectives" is non-standard. More common would be "complementary perspectives"

**Comment by bboc** [comment]
@wolftune thanks for pointing that out, we will fix that. 

> inquire to better understand the feedback, and avoid discussing or judging it.

What we mean is that you do approach the feedback with curiosity, but do not exchange or express arguments or opinions about the feedback. They give you feedback, you make sure you understand what they mean, you take it, and consider it later. Giving and receiving feedback is a delicate matter, and the process is much less painful for both sides if you do it that way.

**Comment by bboc** [comment]
@wolftune fix will be out with the next maintenance release in a couple of days
