### ISSUE TITLE
missing hyphen

### ISSUE THREAD

**Issue by wolftune** [S3-working-group/s3-practical-guide#11]
> A domain is a distinct area of influence, activity and decision making

s/decision making/decision-making

**Comment by bboc** [comment]
It appears that both "decision making" and "decision-making" are valid spellings. We opted for the spelling "decision making" throughout the guide.

**Comment by wolftune** [comment]
Yes, of course both are valid spellings. I was not suggesting that it should always be hyphenated. I was only suggesting that the hyphen would be appropriate in this specific sentence. I still think that, but it's not enough to bother caring about. I won't go into the details, but there are cases where hyphenation is preferred for a specific context. It's very subtle though.
