### ISSUE TITLE
Glossary needs correct markup and anchor links

### ISSUE THREAD

**Issue by wolftune** [S3-working-group/s3-practical-guide#15]
https://patterns.sociocracy30.org/glossary.html just has `strong` tags in the html. These should instead be `dd` tags within a `dl` (definition list) and they should have anchor links so that one can link such as https://patterns.sociocracy30.org/glossary.html#objection which isn't possible now.

**Comment by bboc** [comment]
That is a known issue, see https://github.com/S3-working-group/s3-practical-guide/blob/d5bcf72734adcca946e1cda36586b17f34ad65df/todo.taskpaper#L53

As we currently don't need that feature within the practical guide, that is not particularly high on the list of updates. I'll take a look next time I make larger changes to the renderer.

**Comment by bboc** [comment]
Implemented.
