### ISSUE TITLE
Build instructions unclear

### ISSUE THREAD

**Issue by thoni56** [S3-working-group/s3-practical-guide#17]
I'm having difficulties building the PDF using the supplied instructions. `./build.sh` fails with an indication of `mdslides` missing. I have tried to understand what

> relies on mdtools

actually means. Going to https://github.com/bboc/mdtools doesn't really help since that repo is also unclear about how to use it, and there seems to be no `mdslides` command hiding in there.

Backgound: I'm translating the guide into Swedish but wanted to build the original before attempting to download and insert the translated files from Crowdin.

**Comment by bboc** [comment]
If you install mdtools via make init, it also adds the mudslides command, see https://github.com/bboc/mdtools/blob/121f67ee65cb94ced1d61fd5517ee38f23cb1b47/setup.py#L32. 

For all the other languages, I download the translations and build the site and the downloads, because that requires access to the web server anyway.

**Comment by thoni56** [comment]
Ok, in my environment (Linux, Python 2.7.17) `make init` in mdtools did not install the `mdslides` command. It installed all dependencies, but  did not add `mdslides` wrapper to the PATH (as https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html says it should).

But running

    sudo python setup.py install

seems to do the trick.

**Comment by thoni56** [comment]
In addition (on Linux) I had to install `multimarkdown` from source from https://fletcherpenney.net/multimarkdown/ (the one in Ubuntu repo was *way* to old) and then

    sudo apt install latexmk texlive-xetex fonts-open-sans

With that the guide built cleanly (I think). At least I got a PDF, but it ended with 
```
cd tmp/ebook; latexmk -C
Latexmk: This is Latexmk, John Collins, 18 June 2019, version: 4.65.
Latexmk: Disallowing switch of output file as incompatible
    with file requests.
```

but that might be normal.

**Comment by bboc** [comment]
Thanks for the details, I fixed the makefile and added a section about installation to the README. Those changes will be releases with the upcoming version 2.0 of mdtools (in a week or so).

At least in version 4.55, `latexmk -C` cleans up temporary files, it is not necessary. Maybe I'll simply remove it from the makefile.

**Comment by bboc** [comment]
@thoni56 FYI mdtools 2.0 is available now, but I have yet to update the files in crowdin to work with the new version, so you can't use it just yet.
