### ISSUE TITLE
Navigate per category

### ISSUE THREAD

**Issue by markmarijnissen** [S3-working-group/s3-practical-guide#3]
I find the pattern index overwhelming, yet the 10 categories very helpful.

When I click a pattern, I can navigate "upward" to the category. However, I can't find a list of the 10 categories that is clickable and easy to find.

Is it possible to add a "categories" link in the top menu, which lists the categories?
Alternative: Can you sort the pattern index per category, instead of alphabetically?

**Comment by markmarijnissen** [comment]
Just found the "map" icon! Very helpful, but the could be more clear!

**Comment by bboc** [comment]
There is also a list of all the pattern categories on the homepage:  http://patterns.sociocracy30.org
