### ISSUE TITLE
erroneous footnote markup?

### ISSUE THREAD

**Issue by wolftune** [S3-working-group/s3-practical-guide#5]
At https://patterns.sociocracy30.org/introduction.html under "The New Model of Distribution"

There's this:

```
Everyone can use our resources without our explicit permission, even in a commercial context, or as a basis for building their own resources
[^as long as they share their new resources under the same license].
```

This appears to be an attempt to generate a footnote but where the particular markdown style or the processor rendering the markdown is not correct. But FWIW, I think it could just because a parenthetical and stay in-line — that could work fine too rather than making it a footnote.

---

P.S. Given the sentence being quoted, I just want to emphasize that the Free Culture license is specifically one of the reasons I'm most strongly embracing S3 for my organization Snowdrift.coop (a non-profit, co-op fundraising platform specific to public goods which I would love to one day have helping fund S3 development perhaps; also, we use the same license for all our publications). I hope to keep contributing as much as I can as I keep getting comfortable with S3.

**Comment by bboc** [comment]
Thanks, we fixed that in the last release.
