### ISSUE TITLE
duplicate principle entry

### ISSUE THREAD

**Issue by wolftune** [S3-working-group/s3-practical-guide#7]
see https://patterns.sociocracy30.org/introduction.html

the Principle of Accountability is listed twice but with different formatting

**Comment by wolftune** [comment]
Oh wait, it looks like there's just a sudden, unexpected shift from the list of principles to a single one of them being discussed for some reason. So, maybe this is just somehow out of order or out of context?

**Comment by wolftune** [comment]
Another mess in this same area:

> Every member of the organization is accountable for effectively responding to organizational drivers, both…

and

> Everyone in an organization is accountable for aligning activity with organizational values.

Are semantic duplications. This looks like two versions of a sentence that somehow got both included.

**Comment by bboc** [comment]
> Oh wait, it looks like there's just a sudden, unexpected shift from the list of principles to a single one of them being discussed for some reason. So, maybe this is just somehow out of order or out of context?

It's the first principle that we discuss in more detail, we will add similar sections for the other six principles in the future. 

> Another mess in this same area:
> 
> > Every member of the organization is accountable for effectively responding to organizational drivers, both…
> 
> and
> 
> > Everyone in an organization is accountable for aligning activity with organizational values.
> 
> Are semantic duplications. This looks like two versions of a sentence that somehow got both included.

In fact the semantic duplication is with the first sentence, as organisational values are an agreement governing any domain inside the organization. As many readers might not be aware of that, it still makes sense to point out values in particular.

> Act within the constraints of any agreements governing domains you are accountable for, including the organization itself, teams you are part of, and roles you keep.

**Comment by wolftune** [comment]
I'm not sure I follow as this was stuff I reviewed over a year ago. But I think if a sentence is going to be basically duplicated, it makes sense to quote it in one section or another, such as with a blockquote. So, perhaps the called-out summary bit will be treated as a quote from the longer paragraph.

Anything that connects the duplication both visually and ideally semantically in the markup would help. *Knowing* that a bit is an excerpt from elsewhere or that the longer thing is starting by reviewing the basic bit from before is very helpful to follow the flow.
